### ISSUE TITLE
HOW TO INPUT MANY QUERY?

### ISSUE THREAD

**Issue by yayangkasep** [Freddywhest/MoonbixBot#3]
is there any wrong format in queryIds.json?
![image](https://github.com/user-attachments/assets/87d76272-0048-4c81-834e-7048400ceb97)
![image](https://github.com/user-attachments/assets/1f5f8d89-cc7b-4227-9c21-31a7c253a113)

**Comment by 0xsiwant** [comment]
Settings like this

{
  "account1": "query_id",
  "account2": "query_id"
}

**Comment by yayangkasep** [comment]
> Settings like this
> 
> { "account1": "query_id", "account2": "query_id" }

How to change the delay time for each query?
